local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>bf', builtin.find_files, {})
vim.keymap.set('n', '<leader>bw', builtin.live_grep, {})
vim.keymap.set('n', '<leader>bb', builtin.buffers, {})
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
